before_script:
 - (cd node_modules/mosca/node_modules && rm -rf ascoltatori && ln -s ../../.. ascoltatori)
script:
 - make publish-coverage
language: node_js
node_js:
  - 0.8
  - 0.10
services:
  - rabbitmq
  - redis-server
  - mongodb
